### ISSUE TITLE
Spring boot latest release version availability

### ISSUE THREAD

**Issue by hemalathamoorthy** [hzpz/mongeez-spring-boot-starter#12]
Hello @hzpz 
Its good to see the support for spring boot 2 version already in master.  When can we expect them published as we are really in need of them. 

Thanks 
Hema

**Comment by hzpz** [comment]
Hey @hemalathamoorthy, expect a release on friday.

**Comment by hemalathamoorthy** [comment]
Okay thanks @hzpz

**Comment by hzpz** [comment]
I had some trouble releasing to Central last week. Trying again right now. Sorry for the delay.
