### ISSUE TITLE
Q: How about making mongeez a required dependency?

### ISSUE THREAD

**Issue by nikos** [hzpz/mongeez-spring-boot-starter#6]
Thanks for sharing this really helpful spring boot starter package.
Since I think it really the main sense is to let the user easily access mongeez it would be totally fine to make it a non-optional dependency (in pom.xml). Which in turn also would make the usage of your starter even more simple, so that automatically as a transitive dependency mongeez is available.
What do you think?

**Comment by hzpz** [comment]
You have a point there. I was mimicking the behaviour of other starters I encountered. The idea is that you can have the Mongeez starter on the classpath and nothing will happen as long as you don't also have Mongeez (and Spring Data MongoDB for that matter) on the classpath. Let me think about it.

**Comment by nikos** [comment]
"It depends" :-) ... in the case of "mongeez-spring-boot-starter" I would guess nobody would ever think about referencing to "mongeez-spring-boot-starter" if not used together with mongeez, just my 2 cents...

**Comment by hzpz** [comment]
You are right. The starters I was referring to are included in Spring Boot. It makes sense for them to have only optional dependencies to optional third-party libraries. But the Mongeez starter itself is an optional third-party library, so it might as well have other third-party dependencies. I will change the dependencies for the next release.

**Comment by nikos** [comment]
Very cool, thanks & looking forward to the next release
