### ISSUE TITLE
No support for mongodb URI property

### ISSUE THREAD

**Issue by robmoore** [hzpz/mongeez-spring-boot-starter#7]
Maybe I don't understand how MongeezProperties works but it looks like it doesn't pick up the URI value used in setting the application properties (`spring:data:mongodb:uri`). Also, MongeezProperties does not have a uri property. Is there a reason for this or has it just not been implemented yet. If the latter, I'd take a stab at coding something up if you provide a little direction.

One reason this could be beneficial is that if you are using an SSL connection, you can pass in `ssl=true` in the uri whereas it's more involved otherwise.

**Comment by hzpz** [comment]
You are right, there is no URI support in `MongeezProperties`. That is because Mongeez itself does not support URIs. You will have to implement it in Mongeez first before this starter can support URIs.

**Comment by robmoore** [comment]
@hzpz Thanks for the response. It does look like it's possible to use a URI according to the [Mongeez docs](https://github.com/mongeez/mongeez/wiki/How-to-use-mongeez#execute-the-code-using-spring-integration). It seems like it might be possible to have `MongeezProperties` autowired in such a way that it would pick up the URI and create the `MongoURI` object on its own?

**Comment by hzpz** [comment]
The URI in the example you linked is used to create an instance of `Mongo`. You can do the same by setting `spring.data.mongodb.uri` (or using `MongoProperties` directly) as you already pointed out. However, take a look a the constructor of `MongeezDao` (https://github.com/mongeez/mongeez/blob/master/src/main/java/org/mongeez/dao/MongeezDao.java) to see what they (the Mongeez guys) are actually doing with this `Mongo` instance: they call `getServerAddressList()` which seems to ignore any URI parameters.

**Comment by robmoore** [comment]
@hzpz Thanks for the explanation. I've opened a ticket for adding support in [Mongeez](https://github.com/mongeez/mongeez/issues/61).
