### ISSUE TITLE
Consider adding Spring Boot 2 support

### ISSUE THREAD

**Issue by snicoll** [hzpz/mongeez-spring-boot-starter#8]
Relates to https://github.com/spring-projects/spring-boot/issues/13510

We are reviewing our [community starters list](https://github.com/spring-projects/spring-boot/blob/7683d346e31bbe0313a03ce487ee59454665a143/spring-boot-project/spring-boot-starters/README.adoc) and a quick look here suggests that this starter doesn’t yet support Spring Boot 2.

Can you please let us know if/when you plan to support Spring Boot 2?

Thanks!

**Comment by hzpz** [comment]
I will look into it in the next "6 to 8 weeks" and report back. In the meantime, feel free to remove this starter from your list and I will ask to put it back on once it has Spring Boot 2 support.

**Comment by ro11ak** [comment]
Any updates on Spring Boot 2 support?

**Comment by hzpz** [comment]
Unfortunately, no. I currently don't have any time frame either, sorry.
